// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edit20210325.Models;

namespace edit20210325.Migrations
{
    [DbContext(typeof(CASE20210405Context))]
    [Migration("20210511155251_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Chinese_Taiwan_Stroke_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("edit20210325.Models.ConsumerOrderLogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MemberCashInCash")
                        .HasColumnType("int");

                    b.Property<int>("MemberCashInCounts")
                        .HasColumnType("int");

                    b.Property<DateTime>("MemberCashInCrtDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberCashInDays")
                        .HasColumnType("int");

                    b.Property<string>("MemberCashInRemarks1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInRemarks2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsumerOrderLogModels");
                });

            modelBuilder.Entity("edit20210325.Models.DepositOrderLogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CashInId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberCashInCash")
                        .HasColumnType("int");

                    b.Property<DateTime>("MemberCashInCrtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCashInRemarks1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInRemarks2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepositOrderLogModels");
                });

            modelBuilder.Entity("edit20210325.Models.FileLoadInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FileUpDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MmberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileLoadInfoModels");
                });

            modelBuilder.Entity("edit20210325.Models.ManagerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ManagerModels");
                });

            modelBuilder.Entity("edit20210325.Models.MemberCashInModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MemberCashInCash")
                        .HasColumnType("int");

                    b.Property<DateTime>("MemberCashInChgDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MemberCashInCrtDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCashInId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInSpace1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInSpace2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCashInSpace3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MemberCashInModels");
                });

            modelBuilder.Entity("edit20210325.Models.MemberModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MemberChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberGmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberIden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberRemarks1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberRemarks2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSpace1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSpace2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MemberModels");
                });

            modelBuilder.Entity("edit20210325.Models.MemberSaveLogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MemberSaveCash")
                        .HasColumnType("int");

                    b.Property<DateTime>("MemberSaveCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberSaveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSaveRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MemberSaveLogModels");
                });

            modelBuilder.Entity("edit20210325.Models.MemberSaveModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MemberSaveCash")
                        .HasColumnType("int");

                    b.Property<DateTime>("MemberSaveChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MemberSaveCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberSaveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSaveRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSaveSpace1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSaveSpace2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MemberSaveModels");
                });

            modelBuilder.Entity("edit20210325.Models.SalesOrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCounts")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductDays")
                        .HasColumnType("int");

                    b.Property<string>("ProductInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRemarks1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRemarks2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductUnitDays")
                        .HasColumnType("int");

                    b.Property<int>("ProductUnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalesOrderModels");
                });

            modelBuilder.Entity("edit20210325.Models.VideoFreeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("videoCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoIntro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoRemark1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoRemark2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoFreeModels");
                });

            modelBuilder.Entity("edit20210325.Models.VideoPayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("videoImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoIntro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoPayModels");
                });
#pragma warning restore 612, 618
        }
    }
}
